FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y openssh-server && \
    mkdir /var/run/sshd

RUN apt-get install -y git && \
    apt-get install -y python3 && \
    apt-get install -y python3-termcolor && \
    git clone https://github.com/Max-Khoa/security-log-monitor.git \
    cd security-log-monitor 

RUN echo 'root:password' | chpasswd && \
    echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
